### ISSUE TITLE
Fix concurrent modification exception during warmup

### ISSUE THREAD

**Issue by ewjmulder** [ewjmulder/immerse#44]
INFO: Main mixer changed from state NEW to WARMUP
Exception in thread "Warmup Mixer Executor" java.util.ConcurrentModificationException
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1558)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
	at one.util.streamex.AbstractStreamEx.toSet(AbstractStreamEx.java:1219)
	at com.programyourhome.immerse.audiostreaming.mixer.ImmerseMixer.getScenariosInPlayback(ImmerseMixer.java:156)
	at com.programyourhome.immerse.audiostreaming.mixer.ImmerseMixer.hasScenariosInPlayback(ImmerseMixer.java:147)
	at com.programyourhome.immerse.audiostreaming.mixer.ImmerseMixer.lambda$warmup$2(ImmerseMixer.java:246)
	at com.programyourhome.immerse.audiostreaming.mixer.ImmerseMixer.waitFor(ImmerseMixer.java:472)
	at com.programyourhome.immerse.audiostreaming.mixer.ImmerseMixer.warmup(ImmerseMixer.java:246)
	at com.programyourhome.immerse.audiostreaming.mixer.ImmerseMixer.lambda$initialize$0(ImmerseMixer.java:189)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ewjmulder** [comment]
Reason is overlap of collection scenariosInPlayback with inside and outside world. Collection should be synchronized and atomically copied before used in Stream's. Check also other overlapping collections after refactoring.
