### ISSUE TITLE
Use TCP/UDP for live streams, since HTTP has overhead and copy stream uses big buffer intenally

### ISSUE THREAD

**Issue by ewjmulder** [ewjmulder/immerse#75]
We see a 4K default buffer in StreamUtils.copy so that is not benificial for live streams. Plus HTTP overhead is not useful, just go for plain TCP/UDP with unique port serving that particular stream.

For 44.100, Mono and 2 byte sample size, 4K means about 5 millis, so not too bad, but still...

**Comment by ewjmulder** [comment]
Important point about possible use of UDP: speed is good and packet loss acceptable. The only condition is that the packet size is a multitude of the frame size, cause otherwise missing 1 packet will screw up the frame reading.

**Comment by ewjmulder** [comment]
Finally got it to work! Road to success had a few bumps (put it more detailed documentation?):
- Mic input stream turned out to hand over the data in chunks, for internal mic even 125 mc per time. This is hardware dependent (USB sound cards have 20 ms) and of course sets a limit on the min latency of the whole solution. So having the input buffer too small will loose data.
- When using a large buffer & large packet size: fill is much less frequent then read and after one read it'll stop cause no align (when align/fill were in the loop previously)
- When aligning before read and large packet size it wil work quite well, but if packet size is not exactly the same as the amount of bytes getting ready from stream each time, there will be 'interference' when some times there are 0 and sometimes 2 chunks at once, which causes some hickups
- Final solution: independent of large chunks, choose a (very) small packet size. UDP is fast enough to deliver them in one or a few ms. Then the 'interference' will be for such small amounts it does not matter in playback. The input buffer can be very big, only when playback has a slowdown this causes the latency to increase, cause the buffer is big enough to accomodate that. So in practice you should choose an inpu buffer size of chunk size + read size + a few percent margin.

**Comment by ewjmulder** [comment]
Some background: latency in digital audio processing is a big thing for musicians. Supposendy there are quite low latency USB sound cards / microphones available (+- 5 ms), but there will always be a delay.

**Comment by ewjmulder** [comment]
Some other related thoughts / todo's:
- Think about the difference between live and UDP: what needs which settings?
- Refactor in such a way it's easy to config non-live and live/UDP for audio resource and related data
- UDP AudioResource should supply a buffer size (in ms?!) to use for that resource, depending on the chunk size the data becomes availabel
- Think about it 'on paper' (draw) and have a good calculation for the buffer size taking into account: input suggested buffer (ms), mixer step read chunk (ms), plus some slack for mismatching size 'interference'. Draw out worst case scenario, so not just 'add a few %'.
- Write a util method to get to the number described above
- Write a util method to get the buffer size of the mic input by actually opening it and getting a few chunks and taking the average of the sizes (in ms). Maybe even warn if the chunks are too different (more than a few percent off)
- A small packet size (1 ms of audio) should also allow for non-matching audio formats to work. The only thing left is to calculate the right buffer size taking the conversion bit rates into account (stereo->mono = half size, one byte -> two bytes double size, etc)

**Comment by ewjmulder** [comment]
Take into account with the above that the chunk size can differ quite a lot, see the output below.

**Comment by ewjmulder** [comment]
For internal laptop speaker
```
Exception in thread "main" java.lang.IllegalStateException: Connection check failed: ConnectException: Connection refused (Connection refused)
	at com.programyourhome.immerse.network.client.ImmerseClient.<init>(ImmerseClient.java:49)
	at com.programyourhome.immerse.network.client.TestNetworkClientLocalLaptopUDP.main(TestNetworkClientLocalLaptopUDP.java:62)
# frames in chunk: 1
# ms in chunk: 0.022675736961451247
# frames in chunk: 6808
# ms in chunk: 154.3764172335601
# frames in chunk: 6912
# ms in chunk: 156.73469387755102
# frames in chunk: 7008
# ms in chunk: 158.91156462585033
# frames in chunk: 7128
# ms in chunk: 161.6326530612245
# frames in chunk: 6608
# ms in chunk: 149.84126984126985
# frames in chunk: 6896
# ms in chunk: 156.3718820861678
# frames in chunk: 6368
# ms in chunk: 144.39909297052154
# frames in chunk: 6376
# ms in chunk: 144.58049886621313
# frames in chunk: 6808
# ms in chunk: 154.3764172335601
# frames in chunk: 6800
# ms in chunk: 154.19501133786846
# frames in chunk: 6368
# ms in chunk: 144.39909297052154
# frames in chunk: 6792
# ms in chunk: 154.01360544217687
# frames in chunk: 6960
# ms in chunk: 157.82312925170066
# frames in chunk: 6680
# ms in chunk: 151.47392290249434
# frames in chunk: 6480
# ms in chunk: 146.93877551020407
# frames in chunk: 6808
# ms in chunk: 154.3764172335601
# frames in chunk: 6728
# ms in chunk: 152.56235827664398
# frames in chunk: 6568
# ms in chunk: 148.93424036281178
# frames in chunk: 6808
# ms in chunk: 154.3764172335601
# frames in chunk: 6512
# ms in chunk: 147.6643990929705
# frames in chunk: 6896
# ms in chunk: 156.3718820861678
# frames in chunk: 7056
# ms in chunk: 160.0
# frames in chunk: 6696
# ms in chunk: 151.83673469387756
# frames in chunk: 7112
# ms in chunk: 161.26984126984127
# frames in chunk: 6472
# ms in chunk: 146.75736961451247
# frames in chunk: 6928
# ms in chunk: 157.09750566893425
# frames in chunk: 6792
# ms in chunk: 154.01360544217687
# frames in chunk: 6896
# ms in chunk: 156.3718820861678
# frames in chunk: 7056
# ms in chunk: 160.0
# frames in chunk: 6192
# ms in chunk: 140.40816326530611
# frames in chunk: 5984
# ms in chunk: 135.69160997732425
# frames in chunk: 6824
# ms in chunk: 154.7392290249433
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6408
# ms in chunk: 145.30612244897958
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6720
# ms in chunk: 152.38095238095238
# frames in chunk: 6800
# ms in chunk: 154.19501133786846
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6088
# ms in chunk: 138.04988662131518
# frames in chunk: 6664
# ms in chunk: 151.11111111111111
# frames in chunk: 6936
# ms in chunk: 157.27891156462584
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 7256
# ms in chunk: 164.53514739229024
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6928
# ms in chunk: 157.09750566893425
# frames in chunk: 6624
# ms in chunk: 150.20408163265304
# frames in chunk: 7032
# ms in chunk: 159.45578231292515
# frames in chunk: 6872
# ms in chunk: 155.82766439909295
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6944
# ms in chunk: 157.46031746031747
# frames in chunk: 6056
# ms in chunk: 137.32426303854874
# frames in chunk: 6880
# ms in chunk: 156.00907029478458
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6864
# ms in chunk: 155.64625850340136
# frames in chunk: 6936
# ms in chunk: 157.27891156462584
# frames in chunk: 6968
# ms in chunk: 158.0045351473923
# frames in chunk: 7000
# ms in chunk: 158.73015873015873
# frames in chunk: 7048
# ms in chunk: 159.81859410430837
# frames in chunk: 6944
# ms in chunk: 157.46031746031747
# frames in chunk: 7000
# ms in chunk: 158.73015873015873
# frames in chunk: 6448
# ms in chunk: 146.21315192743765
# frames in chunk: 6968
# ms in chunk: 158.0045351473923
# frames in chunk: 5696
# ms in chunk: 129.1609977324263
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6992
# ms in chunk: 158.5487528344671
# frames in chunk: 6992
# ms in chunk: 158.5487528344671
# frames in chunk: 6648
# ms in chunk: 150.7482993197279
# frames in chunk: 6936
# ms in chunk: 157.27891156462584
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6904
# ms in chunk: 156.5532879818594
# frames in chunk: 7256
# ms in chunk: 164.53514739229024
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6872
# ms in chunk: 155.82766439909295
# frames in chunk: 6520
# ms in chunk: 147.84580498866214
# frames in chunk: 6592
# ms in chunk: 149.47845804988663
# frames in chunk: 6112
# ms in chunk: 138.59410430839003
# frames in chunk: 6088
# ms in chunk: 138.04988662131518
# frames in chunk: 6928
# ms in chunk: 157.09750566893425
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 7008
# ms in chunk: 158.91156462585033
# frames in chunk: 6904
# ms in chunk: 156.5532879818594
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6880
# ms in chunk: 156.00907029478458
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6640
# ms in chunk: 150.56689342403627
# frames in chunk: 7048
# ms in chunk: 159.81859410430837
# frames in chunk: 6688
# ms in chunk: 151.65532879818593
# frames in chunk: 7096
# ms in chunk: 160.90702947845804
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6864
# ms in chunk: 155.64625850340136
# frames in chunk: 6856
# ms in chunk: 155.46485260770976
# frames in chunk: 6800
# ms in chunk: 154.19501133786846
# frames in chunk: 6944
# ms in chunk: 157.46031746031747
# frames in chunk: 6904
# ms in chunk: 156.5532879818594
# frames in chunk: 6912
# ms in chunk: 156.73469387755102
# frames in chunk: 6544
# ms in chunk: 148.39002267573696
# frames in chunk: 6704
# ms in chunk: 152.01814058956916
# frames in chunk: 7032
# ms in chunk: 159.45578231292515
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6856
# ms in chunk: 155.46485260770976
# frames in chunk: 6552
# ms in chunk: 148.57142857142856
# frames in chunk: 6640
# ms in chunk: 150.56689342403627
# frames in chunk: 7032
# ms in chunk: 159.45578231292515
# frames in chunk: 7072
# ms in chunk: 160.36281179138322
# frames in chunk: 6104
# ms in chunk: 138.4126984126984
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6888
# ms in chunk: 156.19047619047618
# frames in chunk: 6576
# ms in chunk: 149.1156462585034
# frames in chunk: 6992
# ms in chunk: 158.5487528344671
# frames in chunk: 6712
# ms in chunk: 152.19954648526075
# frames in chunk: 6896
# ms in chunk: 156.3718820861678
# frames in chunk: 6896
# ms in chunk: 156.3718820861678
# frames in chunk: 6960
# ms in chunk: 157.82312925170066
# frames in chunk: 7008
# ms in chunk: 158.91156462585033
# frames in chunk: 6904
# ms in chunk: 156.5532879818594
# frames in chunk: 6808
# ms in chunk: 154.3764172335601
# frames in chunk: 6928
# ms in chunk: 157.09750566893425
# frames in chunk: 6472
# ms in chunk: 146.75736961451247
# frames in chunk: 5960
# ms in chunk: 135.14739229024943
# frames in chunk: 6440
# ms in chunk: 146.03174603174602
# frames in chunk: 6400
# ms in chunk: 145.12471655328798
# frames in chunk: 6072
# ms in chunk: 137.68707482993196
# frames in chunk: 5712
# ms in chunk: 129.52380952380952
# frames in chunk: 6072
# ms in chunk: 137.68707482993196
# frames in chunk: 5952
# ms in chunk: 134.96598639455783
# frames in chunk: 6400
# ms in chunk: 145.12471655328798
# frames in chunk: 6368
# ms in chunk: 144.39909297052154
# frames in chunk: 6480
# ms in chunk: 146.93877551020407
# frames in chunk: 6944
# ms in chunk: 157.46031746031747
# frames in chunk: 6448
# ms in chunk: 146.21315192743765
# frames in chunk: 7088
# ms in chunk: 160.72562358276645
# frames in chunk: 6400
# ms in chunk: 145.12471655328798
# frames in chunk: 5704
# ms in chunk: 129.34240362811792
# frames in chunk: 6856
# ms in chunk: 155.46485260770976
# frames in chunk: 6392
# ms in chunk: 144.94331065759636
# frames in chunk: 6376
# ms in chunk: 144.58049886621313
# frames in chunk: 5960
# ms in chunk: 135.14739229024943
# frames in chunk: 5944
# ms in chunk: 134.7845804988662
# frames in chunk: 6808
# ms in chunk: 154.3764172335601
# frames in chunk: 6488
# ms in chunk: 147.1201814058957
# frames in chunk: 6664
# ms in chunk: 151.11111111111111
# frames in chunk: 6800
# ms in chunk: 154.19501133786846
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6408
# ms in chunk: 145.30612244897958
# frames in chunk: 6912
# ms in chunk: 156.73469387755102
# frames in chunk: 6632
# ms in chunk: 150.38548752834467
# frames in chunk: 7072
# ms in chunk: 160.36281179138322
# frames in chunk: 6704
# ms in chunk: 152.01814058956916
# frames in chunk: 6960
# ms in chunk: 157.82312925170066
# frames in chunk: 7272
# ms in chunk: 164.89795918367346
# frames in chunk: 7088
# ms in chunk: 160.72562358276645
# frames in chunk: 6120
# ms in chunk: 138.77551020408163
# frames in chunk: 6600
# ms in chunk: 149.65986394557822
# frames in chunk: 7024
# ms in chunk: 159.27437641723355
# frames in chunk: 5968
# ms in chunk: 135.32879818594103
# frames in chunk: 6824
# ms in chunk: 154.7392290249433
# frames in chunk: 6928
# ms in chunk: 157.09750566893425
# frames in chunk: 6496
# ms in chunk: 147.3015873015873
# frames in chunk: 6824
# ms in chunk: 154.7392290249433
# frames in chunk: 6888
# ms in chunk: 156.19047619047618
# frames in chunk: 6856
# ms in chunk: 155.46485260770976
# frames in chunk: 6568
# ms in chunk: 148.93424036281178
# frames in chunk: 7304
# ms in chunk: 165.6235827664399
# frames in chunk: 6624
# ms in chunk: 150.20408163265304
# frames in chunk: 6104
# ms in chunk: 138.4126984126984
# frames in chunk: 6872
# ms in chunk: 155.82766439909295
# frames in chunk: 6648
# ms in chunk: 150.7482993197279
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6904
# ms in chunk: 156.5532879818594
# frames in chunk: 6928
# ms in chunk: 157.09750566893425
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 5968
# ms in chunk: 135.32879818594103
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6840
# ms in chunk: 155.10204081632654
# frames in chunk: 7016
# ms in chunk: 159.09297052154196
# frames in chunk: 6600
# ms in chunk: 149.65986394557822
# frames in chunk: 6960
# ms in chunk: 157.82312925170066
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6896
# ms in chunk: 156.3718820861678
# frames in chunk: 6800
# ms in chunk: 154.19501133786846
# frames in chunk: 6912
# ms in chunk: 156.73469387755102
# frames in chunk: 6880
# ms in chunk: 156.00907029478458
# frames in chunk: 6872
# ms in chunk: 155.82766439909295
# frames in chunk: 6848
# ms in chunk: 155.28344671201813
# frames in chunk: 6864
# ms in chunk: 155.64625850340136
# frames in chunk: 6832
# ms in chunk: 154.9206349206349
# frames in chunk: 6592
# ms in chunk: 149.47845804988663
# frames in chunk: 7272
# ms in chunk: 164.89795918367346
# frames in chunk: 6664
# ms in chunk: 151.11111111111111
# frames in chunk: 7160
# ms in chunk: 162.35827664399093
# frames in chunk: 6584
# ms in chunk: 149.297052154195
# frames in chunk: 7040
# ms in chunk: 159.63718820861678
# frames in chunk: 6544
# ms in chunk: 148.39002267573696
# frames in chunk: 7008
# ms in chunk: 158.91156462585033
# frames in 200 chunks: 1339641.0
# avg ms in chunk: 151.88673469387754
```

**Comment by ewjmulder** [comment]
The data for the external USB sound card is actually a lot more consistent: always 19, 20 or 21 ms:

```
# frames in chunk: 1
# ms in chunk: 0.022675736961451247
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 971
# ms in chunk: 22.01814058956916
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 837
# ms in chunk: 18.979591836734695
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 927
# ms in chunk: 21.020408163265305
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 882
# ms in chunk: 20.0
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in chunk: 838
# ms in chunk: 19.002267573696145
# frames in chunk: 926
# ms in chunk: 20.997732426303855
# frames in 200 chunks: 175608.0
# avg ms in chunk: 19.910204081632653
```

**Comment by ewjmulder** [comment]
Worry no more! Tinkering with the buffer size has made it possible to get the chunk size way down, for both internal and external sound cards! UDP with low read buffer is now working great and super fast. The whole 'pipeline' can be turned down to about 10-20 ms latency, which is very nice compared to the original attempts.
